# Site settings
title: Sam Spades
email: sam@samspades.ca
description: "Rockabilly"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-light: '#ffffff'
  links: '#219ab3'

# Footer settings
footer: Sam Spades

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/samspadesband
  - title: facebook
    url: https://www.facebook.com/samspadesband

# Build settings
markdown: kramdown
permalink: pretty
